name: Update oc.ubuntu images and trigger oc.software

on:
  push:
    branches:
      - main
jobs:
  update_oc_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BASE_IMAGE_RELEASE: [18.04, 20.04, 21.04]
    steps:
      - name: Clone sources
        run: |
          rm -rf ..?* .[!.]* *
          git -c http.extraheader="Authorization: basic ${{ secrets.TOKEN }}" clone "https://github.com/abcdesktopio/oc.ubuntu.git" .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
 
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push oc.ubuntu.${{ matrix.BASE_IMAGE_RELEASE }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            BASE_IMAGE_RELEASE=${{ matrix.BASE_IMAGE_RELEASE }}
            BASE_IMAGE=ubuntu:${{ matrix.BASE_IMAGE_RELEASE }}
          tags: |
            abcdesktopio/oc.ubuntu.${{ matrix.BASE_IMAGE_RELEASE }}:dev

  dispatch_oc_software:
    runs-on: ubuntu-latest
    needs: update_oc_ubuntu
    steps:
      - name: Dispatch to repository oc.software
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: abcdesktopio/oc.software
          event-type: dispatch-from-oc.ubuntu
