name: Update oc.ubuntu images and trigger oc.software

on:
  push:
    branches:
      - main
jobs:
  update_oc_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BASE_IMAGE_RELEASE: [18.04, 21.04]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive --remote
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
 
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN }}

      - name: Run Buildx openbox.${{ matrix.BASE_IMAGE_RELEASE }}
        run: |
          docker buildx build \
            --build-arg BASE_IMAGE_RELEASE=${{ matrix.BASE_IMAGE_RELEASE }} \
            --build-arg BASE_IMAGE=ubuntu:${{ matrix.BASE_IMAGE_RELEASE }} \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --output "type=image,push=true" \
            --tag abcdesktopio/oc.ubuntu.${{ matrix.BASE_IMAGE_RELEASE }}:dev \
            --file ./Dockerfile .
            
  dispatch_oc_software:
    runs-on: ubuntu-latest
    needs: update_oc_ubuntu
    steps:
      - name: Dispatch to repository oc.software
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: abcdesktopio/oc.software
          event-type: dispatch-from-oc.ubuntu
