name: build_oc.ubuntu
on:
  push:
    branches:
      - main
jobs:
  update_oc_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BASE_IMAGE_RELEASE: ["18.04", "21.04"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive --remote
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
 
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN }}
        
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm/v7, linux/arm64
          push: true
          build-args: |
            BASE_IMAGE_RELEASE=${{ matrix.BASE_IMAGE_RELEASE }}
            BASE_IMAGE=ubuntu:${{ matrix.BASE_IMAGE_RELEASE }}
            TAG=dev
          tags: |
            abcdesktopio/oc.ubuntu.${{ matrix.BASE_IMAGE_RELEASE }}:dev
            
  dispatch_oc_software:
    runs-on: ubuntu-latest
    needs: update_oc_ubuntu
    steps:
      - name: Dispatch to repository oc.software
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: abcdesktopio/oc.software
          event-type: dispatch-from-oc.ubuntu
