name: Update oc.ubuntu.18.04 and trigger oc.software.18.04

on:
  push:
    branches:
      - main
jobs:
  build:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Clone sources
        run: |
          rm -rf ..?* .[!.]* *
          git -c http.extraheader="Authorization: basic ${{ secrets.TOKEN }}" clone "https://github.com/abcdesktopio/oc.ubuntu.18.04.git" .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
 
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push ubuntu:18.04
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            BASE_IMAGE_RELEASE=18.04
            BASE_IMAGE=ubuntu:18.04
          tags: |
            abcdesktopio/oc.ubuntu.18.04:dev
            
      - name: Build and push ubuntu:21.04
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            BASE_IMAGE_RELEASE=21.04
            BASE_IMAGE=ubuntu:21.04
          tags: |
            abcdesktopio/oc.ubuntu.21.04:dev

      - name: Dispatch to repository oc.software.18.04
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: abcdesktopio/oc.software.18.04
          event-type: dispatch-from-oc.ubuntu.18.04
